### ISSUE TITLE
Duplicate `build_platform` in `conda-forge.yml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/soqt-feedstock#14]
Currently `build_platform` is listed twice in `conda-forge.yml`:

https://github.com/conda-forge/soqt-feedstock/blob/e49a8b0dac638b83b39443611037806e5125723b/conda-forge.yml#L1-L2

https://github.com/conda-forge/soqt-feedstock/blob/e49a8b0dac638b83b39443611037806e5125723b/conda-forge.yml#L6-L8

This causes some issues for bot updates and migrations (for [example]( https://github.com/regro/cf-scripts/actions/runs/4495907188/jobs/7910046523#step:8:3750 )), which are unable to parse this

Consolidating to one `build_platform` key in `conda-forge.yml`, would fix this issue

**Comment by looooo** [comment]
should be fixed with: https://github.com/conda-forge/soqt-feedstock/pull/18
